ALTER TABLE cars
ADD COLUMN seat_capacity VARCHAR(50),
    ALTER COLUMN maxim_carry TYPE NUMERIC,
    ALTER COLUMN weight TYPE NUMERIC,
    ALTER COLUMN gross_weight TYPE NUMERIC,
    ALTER COLUMN length TYPE NUMERIC,
    ALTER COLUMN width TYPE NUMERIC,
    ALTER COLUMN height TYPE NUMERIC;