# User Login
# @name tokenAPI
POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
    "identity":"AdminJ",
    "password":"Admin123"
}

###
# car Registration
@hostname = http://127.0.0.1:8080/api
@bearer = {{tokenAPI.response.body.token}}

###
# Fetch cars
GET {{hostname}}/cars?page=1&limit=10
authorization: bearer {{bearer}}

###
# Search cars
GET {{hostname}}/cars?model=Toyota&page=1&limit=25
authorization: bearer {{bearer}}

###
# Fetch car by ID
GET {{hostname}}/car/id/59
authorization: bearer {{bearer}}

###
# Fetch car by ID
PUT {{hostname}}/car/59/status
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "car_status": "InStock"
}


###
# Fetch car by VINN
GET {{hostname}}/car/vin/1HGCM82633A123456
authorization: bearer {{bearer}}

###
# Update car by ID in Japan
# PUT {{hostname}}/car/1/details
# authorization: bearer {{bearer}}
# Content-Type: application/json


###
# Update car by ID in Uganda
PUT {{hostname}}/car/1/sale
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "broker_name": "John Doe",
  "broker_number": "+256-712-345-678",
  "number_plate": "UBH 123A",
  "customer_id": 1,
  "car_status": "InStock", // InTransit, InStock, Sold
  "car_payment_status": "Booked", // Fully Payed, Partially Paid, Booked
  "updated_by": "admin"
}

###
# Update car shipping-invoice id
PUT {{hostname}}/car/1/shipping-invoice
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "car_shipping_invoice_id": 1,
  "updated_by": "admin"
}

###
# Delete car by ID
DELETE  {{hostname}}/car/2
authorization: bearer {{bearer}}

# =================================================
# Car Expenses

###
# Get Car Expenses
GET {{hostname}}/carExpenses?page=1&limit=10
authorization: bearer {{bearer}}

###
# Get Car expenses by Car ID
GET {{hostname}}/car/10/expenses?page=1&limit=10

###
# Get Car expenses by Car ID and expense ID
GET {{hostname}}/car/1/expense/1

###
# Create car expense
POST {{hostname}}/car/expense
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"car_id": 1,
	"description": "COMMISSION",
	"currency": "UGX",
	"amount": 50000,
	"expense_date": "2023-05-01",
  "carrier_name":"", // if description == "Carrier car fee(RISKO)"
	"expense_remark":"",
	"updated_by": "Admin",
  "created_by": "Admin"
}

###
# Update carexpense by ID
PUT {{hostname}}/car/expense/1
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"car_id": 1,
	"description": "VAT (Value Added Tax)",
	"currency": "UGX",
	"amount": 150000,
	"expense_date": "2024-05-01",
	"updated_by": "Admin"
}

###
# Delete carexpense by ID
DELETE {{hostname}}/car/1/expense/2
authorization: bearer {{bearer}}

# =================================================

###
# Get total carexpense by ID
GET {{hostname}}/total-car-expense/2
authorization: bearer {{bearer}}

###
# Get car uploads
GET {{hostname}}/car/uploads?id=1
authorization: bearer {{bearer}}

###
GET {{hostname}}/cars/search?to_company=she
authorization: bearer {{bearer}}

###
GET {{hostname}}/car/dash/1
authorization: bearer {{bearer}}

###
GET {{hostname}}/alerts/search?from_company_id=1&company_id=1
authorization: bearer {{bearer}}

###
# Update alert by ID
PUT {{hostname}}/alert/2
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"view_status": true,
	"updated_by": "Admin"
}


###
POST {{hostname}}/car/all-details
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "car": {"chasis_number": "ABC123456789XYZ",
			"engine_number": "ENG987654321",
			"engine_capacity": "2000cc",
			"frame_number": "FRM123456789",
			"make": "Toyota",
			"car_model": "Corolla",
			"maxim_carry": 5,
			"weight": 1200,
			"gross_weight": 1500,
			"length": 4500,
			"width": 1750,
			"height": 1450,
			"manufacture_year": 2022,
			"first_registration_year": 2023,
			"transmission": "Automatic",
			"body_type": "Sedan",
			"colour": "White",
			"auction": "Yes",
			"currency": "USD",
			"car_millage": 30000,
			"fuel_consumption": "Petro",
			"power_steering": true,
			"power_window": true,
			"abs": true,
			"ads": false,
			"air_brake": false,
			"oil_brake": true,
			"alloy_wheel": true,
			"simple_wheel": false,
			"navigation": true,
			"ac": true,
			"bid_price": 15000.50,
			"vat_tax": 10,
			"purchase_date": "2024-03-02",
			"from_company_id": 2,
			"to_company_id": 1,
			"other_entity":"",
			"destination": "Kampala, Uganda",
			"port": "Port of Yoko",
			"car_shipping_invoice_id": null,
			"car_status_japan": "Exported",
			"broker_name": "",
			"broker_number": "",
			"number_plate": "87788",
			"car_tracker": true,
			"customer_id": null,
			"car_status": "Booked",
			"car_payment_status": "",
			"created_by": "admin",
			"updated_by": "admin"},
  "car_expenses": [
    {
      "description": "Shipping Fee",
      "currency": "USD",
      "amount": 1200.00,
      "dollar_rate": 1.0,
      "expense_date": "2024-03-15",
      "company_name": "ABC Logistics",
	  "destination":"",
	  "expense_vat": 10,
      "expense_remark": "Paid in full",
      "created_by": "admin",
      "updated_by": "admin"
    },
    {
      "description": "Customs Duty",
      "currency": "UGX",
      "amount": 5000000,
      "dollar_rate": 3800,
      "expense_date": "2024-03-18",
      "company_name": "URA",
	  "destination":"",
	  "expense_vat": 10,
      "expense_remark": "Pending clearance",
      "created_by": "admin",
      "updated_by": "admin"
    }
  ]
}


