# User Login
# @name tokenAPI
POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
    "identity":"Admin",
    "password":"Admin123"
}

###
# car Registration
@hostname = http://127.0.0.1:8080/api
@bearer = {{tokenAPI.response.body.token}}

POST {{hostname}}/car
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "chasis_number": "1HGCM82633A123456",
  "engine_number": "ENG123456789",
  "engine_capacity": "2000cc",
  "make": "Toyota",
  "model": "Corolla",
  "maxim_carry": 500,
  "weight": 1200,
  "gross_weight": 1500,
  "length": 4500,
  "width": 1800,
  "height": 1400,
  "manufacture_year": 2020,
  "first_registration_year": 2021,
  "transmission": "Automatic",
  "body_type": "Sedan",
  "colour": "Blue",
  "auction": "Tokyo Auto Auctions",
  "currency": "Yen",
  "millage":40000,
	"fuel_consumption":"Disel",
	"ps": false,
  "pw": false,
  "abs": false,
  "ads": false,
  "aw": false,
  "sw": false,
  "navigation": false,
	"ac": false,  
  "bid_price": 15000000.00,
  "vat_tax": 18.00,
  "dollar_rate": 150,
  "purchase_date": "2024-01-01",
  "from_company_id": 2,
  "to_company_id": 1,
  "destination": "Kampala, Uganda",
  "port": "Port of Yokohama",
  "car_shipping_invoice_id": null,
  "broker_name": "",
  "broker_number": "",
  "vat_tax": null,
  "number_plate": "",
  "customer_id": null,
  "car_status": "",
  "car_payment_status": "",
  "created_by": "admin",
  "updated_by": "admin"
}

###
# Fetch cars
GET {{hostname}}/cars?page=1&limit=10
authorization: bearer {{bearer}}

###
# Search cars
GET {{hostname}}/cars?model=Toyota&page=1&limit=25
authorization: bearer {{bearer}}

###
# Fetch car by ID
GET {{hostname}}/car/id/1
authorization: bearer {{bearer}}

###
# Fetch car by VINN
GET {{hostname}}/car/vin/1HGCM82633A123456
authorization: bearer {{bearer}}

###
# Update car by ID in Japan
PUT {{hostname}}/car/1/details
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "chasis_number": "1HGCM82633A123456",
  "engine_number": "ENG123456789",
  "engine_capacity": "2000cc",
  "make": "Toyota",
  "model": "Corolla",
  "maxim_carry": 500,
  "weight": 1200,
  "gross_weight": 1500,
  "length": 4500,
  "width": 1800,
  "height": 1400,
  "manufacture_year": 2020,
  "first_registration_year": 2021,
  "transmission": "Automatic",
  "body_type": "Sedan",
  "colour": "Blue",
  "auction": "Tokyo Auto Auctions",
  "currency": "Yen",
  "millage":40000,
	"fuel_consumption":"",
	"ps": false,
  "pw": false,
  "abs": false,
  "ads": false,
  "aw": false,
  "sw": false,
  "navigation": false,
	"ac": false,  
  "bid_price": 15000000.00,
  "vat_tax": 18.00,
  "dollar_rate": 150,
  "purchase_date": "2024-01-01",
  "from_company_id": 2,
  "to_company_id": 1,
  "destination": "Kampala, Uganda",
  "port": "Port of Yokohama",
  "car_shipping_invoice_id": null,
  "updated_by": "admin"
}

###
# Update car by ID in Uganda
PUT {{hostname}}/car/1/sale
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "broker_name": "John Doe",
  "broker_number": "+256-712-345-678",
  "number_plate": "UBH 123A",
  "customer_id": 1,
  "car_status": "In stock",
  "car_payment_status": "Booked",
  "updated_by": "admin"
}

###
# Update car shipping-invoice id
PUT {{hostname}}/car/1/shipping-invoice
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "car_shipping_invoice_id": 1,
  "updated_by": "admin"
}

###
# Delete car by ID
DELETE  {{hostname}}/car/2
authorization: bearer {{bearer}}

# =================================================
# Car Expenses

###
# Get Car Expenses
GET {{hostname}}/carExpenses?page=1&limit=10
authorization: bearer {{bearer}}

###
# Get Car expenses by Car ID
GET {{hostname}}/car/1/expenses?page=1&limit=10

###
# Get Car expenses by Car ID and expense ID
GET {{hostname}}/car/1/expense/1

###
# Create car expense
POST {{hostname}}/car/expense
authorization: bearer {{bearer}}
Content-Type: application/json

# {
# 	"car_id": 1,
# 	"description": "VAT (Value Added Tax)",
# 	"currency": "UGX",
# 	"amount": 100000,
# 	"expense_date": "2024-01-01",
# 	"created_by": "Gadafi",
# 	"updated_by": "Admin"
# }

{
	"car_id": 1,
	"description": "COMMISSION",
	"currency": "UGX",
	"amount": 50000,
	"expense_date": "2023-05-01",
	"updated_by": "DN"
}

###
# Update carexpense by ID
PUT {{hostname}}/car/expense/1
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"car_id": 1,
	"description": "VAT (Value Added Tax)",
	"currency": "UGX",
	"amount": 150000,
	"expense_date": "2024-05-01",
	"updated_by": "Admin"
}

###
# Delete carexpense by ID
DELETE {{hostname}}/car/1/expense/2
authorization: bearer {{bearer}}

# =================================================

###
# Get total carexpense by ID
GET {{hostname}}/total-car-expense/1
authorization: bearer {{bearer}}

###
# Get car uploads
GET {{hostname}}/car/uploads?id=1
authorization: bearer {{bearer}}

###
GET {{hostname}}/cars/search?from_company_id=2&make=Toyota
authorization: bearer {{bearer}}

###
GET {{hostname}}/car/dash
authorization: bearer {{bearer}}