# @name tokenAPI
POST https://clims.health.go.ug/api/auth/login
content-type: application/json

{
    "identity":"Admin",
    "password":"Admin123"
}

###
@bearer = {{tokenAPI.response.body.token}}
GET https://clims.health.go.ug/api/users
authorization: bearer {{bearer}}

###
PATCH https://clims.health.go.ug/api/user/5
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"surname":   "Kizza",
	"firstname": "Joan",
	"othername": "",
	"gender":    "Female",
	"title":     "Cashier",
	"username":  "JoanKizza",
	"email":     "joan.kizza@gmail.com",
	"password":  "password",
	"company_id": 2,
	"group_id":   1,
	"created_by": "admin",
	"updated_by": ""
}