
@hostname = https://clims.health.go.ug/api
# @name tokenAPI
POST {{hostname}}/auth/login
content-type: application/json

{
    "identity":"Admin",
    "password":"Admin123"
}

###
@bearer = {{tokenAPI.response.body.token}}
GET {{hostname}}/users
authorization: bearer {{bearer}}

###
POST {{hostname}}/user
authorization: bearer {{bearer}}
Content-Type: application/json

{
	"surname":   "Kizza",
	"firstname": "Joan",
	"othername": "",
	"gender":    "Female",
	"title":     "Cashier",
	"username":  "JoanKizza",
	"email":     "joan.kizza@gmail.com",
	"password":  "password",
	"company_id": 2,
	"group_id":   3,
	"created_by": "admin",
	"updated_by": ""
}

###
# Get total carexpense by ID
GET {{hostname}}/total-car-expense/1
authorization: bearer {{bearer}}