# User Login
# @name tokenAPI
POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
    "identity":"Admin",
    "password":"Admin123"
}

###
# customer Registration
@hostname = http://127.0.0.1:8080/api
@bearer = {{tokenAPI.response.body.token}}

POST {{hostname}}/shipping/invoices
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "invoice_no": "FGTG908",
  "ship_date": "1989-05-15",
  "currency": "Yen",
  "total_cost": 77777,
  "vessel_name": "MALL MARINA",
  "from_location": "JAK",
  "to_location": "MOMBASA",
  "created_by": "admin",
  "updated_by": "admin"
}

# {
#   "surname": "Hannah",
#   "firstname": "John",
#   "othername": "Bibianah",
#   "gender": "Female",
#   "nationality": "Ugandan",
#   "age": 35,
#   "dob": "1994-05-15",
#   "telephone": "+256-701-234-567",
#   "email": "bibana.hana@example.com",
#   "nin": "CM8901234567ABCD",
#   "created_by": "admin",
#   "updated_by": "admin"
# }

###
# Fetch Invoices
GET {{hostname}}/shipping/invoices?page=1&limit=50
authorization: bearer {{bearer}}

###
# Fetch invoice by ID
GET {{hostname}}/shipping/invoice/1
authorization: bearer {{bearer}}

###
# Fetch invoice by ID
GET {{hostname}}/shipping/invoice/no/FGTG908
authorization: bearer {{bearer}}

###
# Update invoice by ID
PUT {{hostname}}/shipping/invoice/1
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "invoice_no": "FGTG908",
  "ship_date": "1989-06-15",
  "currency": "Yen",
  "total_cost": 828829,
  "vessel_name": "MALL MARINA",
  "from_location": "JAK",
  "to_location": "MOMBASA",
  "created_by": "admin",
  "updated_by": "admin",
  "car_ids": [45]
}

###
# Delete invoice by ID
DELETE {{hostname}}/shipping/invoice/1
authorization: bearer {{bearer}}

###
# Delete invoice by ID
PATCH {{hostname}}/shipping/invoice/1/lock
authorization: bearer {{bearer}}


