# User Login
# @name tokenAPI
POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
    "identity":"Admin",
    "password":"Admin123"
}

###
@hostname = http://127.0.0.1:8080/api/meta
@bearer = {{tokenAPI.response.body.token}}

GET {{hostname}}/weights
authorization: bearer {{bearer}}

###
GET {{hostname}}/currency
authorization: bearer {{bearer}}

###
GET {{hostname}}/lengths
authorization: bearer {{bearer}}

###
GET {{hostname}}/expenses
authorization: bearer {{bearer}}


###
GET {{hostname}}/ports?name=Port of Yo
authorization: bearer {{bearer}}
