# User Login
# @name tokenAPI
POST http://127.0.0.1:8080/api/auth/login
content-type: application/json

{
    "identity":"AdminD",
    "password":"Admin123"
}

###
# Sale Registration
@hostname = http://127.0.0.1:8080/api
@bearer = {{tokenAPI.response.body.token}}

POST {{hostname}}/sale
authorization: bearer {{bearer}}
Content-Type: application/json

{
    "total_price": 10525000.00,
    "sale_date": "2025-01-28",
    "car_id": 1,
    "company_id": 1,
    "is_full_payment": false,
    "payment_period": 12,
    "created_by": "admin",
    "updated_by": "admin"
}

###
# Fetch sales
GET {{hostname}}/sales?page=1&limit=10
authorization: bearer {{bearer}}

###
# Fetch sale by ID
GET {{hostname}}/sale/1
authorization: bearer {{bearer}}

###
# Update sale by ID
PUT {{hostname}}/sale/1
authorization: bearer {{bearer}}
Content-Type: application/json

{
    "total_price": 225000.00,
    "sale_date": "2025-02-28",
    "car_id": 1,
    "company_id": 1,
    "is_full_payment": true,
    "payment_period": 0,
    "created_by": "admin",
    "updated_by": "admin"
}

###
# Delete sale by ID
DELETE  {{hostname}}/sale/1
authorization: bearer {{bearer}}

# ====================

###
# INVOICE
POST {{hostname}}/invoice
authorization: bearer {{bearer}}
Content-Type: application/json

{
    "amount_payed": 1500000.00,
    "payment_date": "2025-02-28",
    "sale_id": 1,
    "created_by": "admin",
    "updated_by": "admin"
}

###
GET {{hostname}}/invoices?page=1&limit=10
authorization: bearer {{bearer}}

###
GET {{hostname}}/invoice/1/1
authorization: bearer {{bearer}}

# ====================

###
# Payment mode
POST {{hostname}}/payment
authorization: bearer {{bearer}}
Content-Type: application/json

{
    "mode_of_payment": "Mobile money",
    "transaction_id": "HDHDU363773LKS",
    "sale_payment_id": 1,
    "created_by": "admin",
    "updated_by": "admin"
}

###
GET {{hostname}}/payments?page=1&limit=10
authorization: bearer {{bearer}}

###
GET {{hostname}}/payment/1/1
authorization: bearer {{bearer}}

###
GET {{hostname}}/payment/Mobile money
authorization: bearer {{bearer}}

# ====================

###
# Payment Deposit
POST {{hostname}}/deposit
authorization: bearer {{bearer}}
Content-Type: application/json

{
    "bank_name": "Absa Bank",
    "bank_account": "123338484492",
    "bank_branch": "Wandegeya",
    "amount_deposited": 2000000,
    "date_deposited": "2025-03-01",
    "deposit_scan": "",
    "sale_payment_id": 1,
    "created_by": "admin",
    "updated_by": "admin"
}

###
GET {{hostname}}/deposits
authorization: bearer {{bearer}}

###
GET {{hostname}}/deposit/1/1
authorization: bearer {{bearer}}

###
GET {{hostname}}/deposit/Absa Bank
authorization: bearer {{bearer}}


# Sale statement
###
GET {{hostname}}/sale/statement/1
authorization: bearer {{bearer}}


###
# Sale Payment Deposit
POST {{hostname}}/sale/all-details
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "sale": {
    "total_price": 15000,
    "dollar_rate": 3800,
    "sale_date": "2025-07-27",
    "car_id": 59,
    "company_id": 2,
    "customer_id": 1,
    "is_full_payment": false,
    "initial_payment": 5000,
    "payment_period": 3,
    "created_by": "admin",
    "updated_by": "admin"
  },
  "sale_payments": [
    {
      "amount_payed": 5000,
      "payment_date": "2025-07-27",
      "created_by": "admin",
      "updated_by": "admin",
      "payment_mode": {
        "mode_of_payment": "BankTransfer",
        "transaction_id": "TXN-001",
        "created_by": "admin",
        "updated_by": "admin"
      }
    },
    {
      "amount_payed": 3000,
      "payment_date": "2025-08-10",
      "created_by": "admin",
      "updated_by": "admin",
      "payment_mode": {
        "mode_of_payment": "MobileMoney",
        "transaction_id": "TXN-002",
        "created_by": "admin",
        "updated_by": "admin"
      }
    }
  ]
}

###
# Sale Payment Deposit
PUT {{hostname}}/sale/1/all-details
authorization: bearer {{bearer}}
Content-Type: application/json

{
  "sale": {
    "total_price": 15000,
    "initial_payment": 8000,
    "payment_period": 6,
    "sale_date": "2025-07-25",
    "car_id": 12,
    "company_id": 3,
    "customer_id": 1,
    "created_by": "admin",
    "updated_by": "admin"
  },
  "sale_payments": [
    {
      "amount_payed": 8000,
      "payment_date": "2025-07-26",
      "created_by": "admin",
      "updated_by": "admin",
      "payment_mode": {
        "mode_of_payment": "Cash",
        "transaction_id": "TXN001",
        "created_by": "admin",
        "updated_by": "admin"
      }
    }
  ]
}
